// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiDsX800tAQZIyXAncNDEBGRTn7PPVjSA',
    appId: '1:447738809519:web:9288271a97b095813ed85a',
    messagingSenderId: '447738809519',
    projectId: 'petcare-3aad5',
    authDomain: 'petcare-3aad5.firebaseapp.com',
    storageBucket: 'petcare-3aad5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdw0yjbHI930sdryMTIRfRogSihSfXwHw',
    appId: '1:447738809519:android:488e354a574a3ccf3ed85a',
    messagingSenderId: '447738809519',
    projectId: 'petcare-3aad5',
    storageBucket: 'petcare-3aad5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLi1t3k8dUjFJW1KNPJr30cUc1sC2P2KY',
    appId: '1:447738809519:ios:883d0c541b00486e3ed85a',
    messagingSenderId: '447738809519',
    projectId: 'petcare-3aad5',
    storageBucket: 'petcare-3aad5.appspot.com',
    iosBundleId: 'com.example.petCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLi1t3k8dUjFJW1KNPJr30cUc1sC2P2KY',
    appId: '1:447738809519:ios:516762ea220b61923ed85a',
    messagingSenderId: '447738809519',
    projectId: 'petcare-3aad5',
    storageBucket: 'petcare-3aad5.appspot.com',
    iosBundleId: 'com.example.petCare.RunnerTests',
  );
}
